-- Executar no SQL Server (SSMS). WORK_HEADER_ID = id legado do projeto (ex.: 4698).
-- Use os resultados para montar o POST /v1/AreaActivity ou, de preferência, chame a API:
--   POST /v1/Migration/from-sqlserver?legacyProjectId=4698

DECLARE @ProjectId INT = 4698;

-- Áreas do projeto
SELECT
    B.WORK_AREA_ID,
    B.AREA,
    B.METROS2,
    B.WORK_HEADER_ID
FROM dbo.WORK_AREA AS B WITH (NOLOCK)
WHERE B.WORK_HEADER_ID = @ProjectId
ORDER BY B.WORK_AREA_ID;

-- Tarefas por área (para cruzar com WORK_AREA_ID ao montar "items")
SELECT
    B.WORK_AREA_ID,
    D.TAREFA_NUMERO,
    D.NOME_TAREFA,
    D.PERIODO,
    C.ORDEM,
    C.FREQUENCIA AS FREQUENCIA_DIAS,
    FREQ.FREQUENCIA AS FREQUENCIA_NOME
FROM dbo.WORK_HEADER AS A WITH (NOLOCK)
INNER JOIN dbo.WORK_AREA AS B WITH (NOLOCK)
    ON B.WORK_HEADER_ID = A.WORK_HEADER_ID
INNER JOIN dbo.WORK_TAREFAS AS C WITH (NOLOCK)
    ON C.WORK_AREA_ID = B.WORK_AREA_ID
INNER JOIN dbo.WORK_TBL_TAREFAS AS D WITH (NOLOCK)
    ON D.WORK_TBL_TAREFAS_ID = C.WORK_TBL_TAREFAS_ID
LEFT JOIN dbo.WORK_TBL_FREQ AS FREQ WITH (NOLOCK)
    ON C.FREQUENCIA = FREQ.DIAS
WHERE A.WORK_HEADER_ID = @ProjectId
ORDER BY B.WORK_AREA_ID, C.ORDEM, D.TAREFA_NUMERO;
