SELECT
	 AREA.AREA AS [name]
	,'' AS [description]
	,CAST(0 AS BIT) AS [quickTask]
	,CAST(AREA.METROS2 AS INT) AS [totalM2]
	,NULL AS [area.employeeId]
	,CONCAT('Header-', CAST(DENSE_RANK() OVER (ORDER BY AREA.WORK_AREA_ID) AS VARCHAR)) AS [headerId]
	,DENSE_RANK() OVER (ORDER BY AREA.WORK_AREA_ID) AS [orderBy]
	,(
		SELECT
			 CAST(ROW_NUMBER() OVER(PARTITION BY AREA.WORK_AREA_ID ORDER BY AREA.WORK_AREA_ID) AS VARCHAR) AS [items.itemId]
			,TAREFA_ITEM.NOME_TAREFA AS [items.name]
			,TAREFA.ORDEM AS [items.orderBy]
			,CASE
				WHEN FREQ.DIAS = 1 THEN 'yearly'
				WHEN FREQ.DIAS = 2 THEN 'semi-annual'
				WHEN FREQ.DIAS = 4 THEN 'quarterly'
				WHEN FREQ.DIAS = 6 THEN 'bimonthly'
				WHEN FREQ.DIAS = 12 THEN 'monthly'
				WHEN FREQ.DIAS = 26 THEN 'biweekly'
				WHEN FREQ.DIAS = 52 THEN 'weekly'
				WHEN FREQ.DIAS = 365 THEN 'everyday'
				--	weekend: 'Fim de Semana',
				ELSE FREQ.FREQUENCIA
			 END AS [items.frequency.type]
		FROM
			WORK_TAREFAS AS TAREFA
			INNER JOIN WORK_TBL_TAREFAS AS TAREFA_ITEM ON
			(
				TAREFA.WORK_TBL_TAREFAS_ID = TAREFA_ITEM.WORK_TBL_TAREFAS_ID
			)
			INNER JOIN WORK_TBL_FREQ AS FREQ ON
			(
				TAREFA.FREQUENCIA = FREQ.DIAS
			)
		WHERE 
			AREA.WORK_AREA_ID = TAREFA.WORK_AREA_ID
		FOR JSON PATH
	) AS [items]
	,AREA.WORK_HEADER_ID AS [projectId]
	,NULL AS [frequency]
FROM
	WORK_AREA AS AREA
WHERE
	AREA.WORK_HEADER_ID IN (4973)
	AND AREA.WORK_AREA_ID IN (60911, 60913)
FOR JSON PATH
;
