-- select dados projeto
SELECT
	 PROJETO.WORK_HEADER_ID AS [legacyId]
	,PROJETO.NOMEPROJETO AS [name]
	,CAST(PROJETO.TOTALM2 AS INT) AS [totalM2]
	,CAST(PROJETO.DIASANO AS INT) AS [daysYear]
	,CAST(PROJETO.FATOR AS NUMERIC(10, 1)) AS [factor]
	,PROJETO.END1 AS [address]
	,PROJETO.CONTATO AS [contact]
	,PROJETO.TELEFONE AS [telephoneNumber]
	,PROJETO.CELULAR AS [cellphoneNumber]
	,PROJETO.DATACAD AS [registrationDate]
	,PROJETO.NIVEL_PROJETO AS [level]
FROM
	WORK_HEADER AS PROJETO
--FOR JSON AUTO
;
